### ISSUE TITLE
`step_executor.py` attribute bug

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1044]
Got this error message today, but without trying to come up the MWE I'm wondering if it is obvious to eyeball and fix?

```
TRACE: Set _index to 0 of type <class 'int'>
  File "/scratch/midway2/gaow/miniconda3/lib/python3.6/site-packages/sos/step_executor.py", line 1920, in run
    res = Base_Step_Executor.run(self)
Traceback (most recent call last):
  File "/scratch/midway2/gaow/miniconda3/lib/python3.6/site-packages/sos/step_executor.py", line 1920, in run
    res = Base_Step_Executor.run(self)
  File "/scratch/midway2/gaow/miniconda3/lib/python3.6/site-packages/sos/step_executor.py", line 1512, in run
    if not g.valid() and statement[0] != ':':
AttributeError: 'list' object has no attribute 'valid'
DEBUG: Step extract_sumstats_1 sends exception 'list' object has no attribute 'valid'
DEBUG: Worker SoS_Worker-1 completes request 'step', <sos.parser.SoS_Step object at 0x7f..., ... (7 items)
DEBUG: Master receive a result AttributeError("'list' object has n...
DEBUG: Master received an exception
DEBUG: 3c5d884b72fecaae: 1 slots released from 1 active, 0 remain
  File "/scratch/midway2/gaow/miniconda3/lib/python3.6/site-packages/sos/__main__.py", line 372, in cmd_run
    executor.run(args.__targets__, mode='dryrun' if args.dryrun else 'run')
Traceback (most recent call last):
  File "/scratch/midway2/gaow/miniconda3/lib/python3.6/site-packages/sos/__main__.py", line 372, in cmd_run
    executor.run(args.__targets__, mode='dryrun' if args.dryrun else 'run')
  File "/scratch/midway2/gaow/miniconda3/lib/python3.6/site-packages/sos/workflow_executor.py", line 1409, in run
    raise exec_error
sos.workflow_executor.ExecuteError: [extract_sumstats_1]: 'list' object has no attribute 'valid'
[extract_sumstats]: 1 pending step: extract_sumstats_2
ERROR: [extract_sumstats_1]: 'list' object has no attribute 'valid'
```

**Comment by gaow** [comment]
This is actually caused by a bad input on my end, so i should be able to reproduce with MWE if you need it. When my input is good there is no problem.

**Comment by BoPeng** [comment]
In what sense the input is bad?

**Comment by gaow** [comment]
Here, easy to reproduce, I should have looked and provided it:

```
[1]
input: glob.glob('*.non-existing-suffix'), group_by=1, concurrent=True
print(_input)
```

it's `glob.glob` problem.
