### ISSUE TITLE
Task relics removed too soon?

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1148]
Recently there is a patch added to clean up `task` relics from `~/.sos`. But perhaps the clean up happened too soon? See what had happened to me below:

```
INFO: a9aa88356aab8982 submitted to midway2 with job id 55932834
INFO: 7eecca1e8bb605bd submitted to midway2 with job id 55932835
INFO: 178a812c927f243b submitted to midway2 with job id 55932836
INFO: b66e35fc20e26204 submitted to midway2 with job id 55932837
INFO: b9763c77cb542bf7 submitted to midway2 with job id 55932838
INFO: 353d28e566197766 submitted to midway2 with job id 55932839
INFO: c275cf81ef010b80 submitted to midway2 with job id 55932840
  File "/scratch/midway2/gaow/miniconda3/lib/python3.6/site-packages/sos/__main__.py", line 965, in cmd_status
    age=args.age, tags=args.tags, status=args.status)
Traceback (most recent call last):
  File "/scratch/midway2/gaow/miniconda3/lib/python3.6/site-packages/sos/__main__.py", line 965, in cmd_status
    age=args.age, tags=args.tags, status=args.status)
  File "/scratch/midway2/gaow/miniconda3/lib/python3.6/site-packages/sos/tasks.py", line 841, in print_task_status
    raw_status = check_tasks([x[0] for x in all_tasks], check_all)
  File "/scratch/midway2/gaow/miniconda3/lib/python3.6/site-packages/sos/tasks.py", line 780, in check_tasks
    check_task, [(x, status_cache.get(x, {})) for x in tasks])
  File "/scratch/midway2/gaow/miniconda3/lib/python3.6/multiprocessing/pool.py", line 274, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/scratch/midway2/gaow/miniconda3/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: '/home/gaow/.sos/tasks/92c64206254fe264.sh'
ERROR: [Errno 2] No such file or directory: '/home/gaow/.sos/tasks/92c64206254fe264.sh'
WARNING: Check output of sos status d1ef9c2ae50eaa76 da268b75249a97b1 4a69e535c353758f 982f214f8703d62d 700d3f31a1145bce 2807ced1edb14da9 8ba8dac9f2de7008 00561c97f20f88ed 49c9bc46a2560228 67c8976b3c7908be 757ad451cf922b8f 6a78eeabb589a8c9 2390fbd9b30e818d 6b3d52f40e9d19bd 8225757dbf916793 7eecca1e8bb605bd b66e35fc20e26204 353d28e566197766 92c64206254fe264 97514fc78b441504 f2117921aa735327 f21f20ec8e9379d5 f5ef96d58e4deb41 6958a1acae5243d3 71dd1ab5f9d7f109 2b2aedaf765a1e41 355cfd4e52502155 0094e33db6d14e63 6f0b690799f0c904 06203886dced107a a5c9d41a44ad8db7 a9aa88356aab8982 178a812c927f243b b9763c77cb542bf7 c275cf81ef010b80 -v 3   --numeric-times    failed: Command 'sos status d1ef9c2ae50eaa76 da268b75249a97b1 4a69e535c353758f 982f214f8703d62d 700d3f31a1145bce 2807ced1edb14da9 8ba8dac9f2de7008 00561c97f20f88ed 49c9bc46a2560228 67c8976b3c7908be 757ad451cf922b8f 6a78eeabb589a8c9 2390fbd9b30e818d 6b3d52f40e9d19bd 8225757dbf916793 7eecca1e8bb605bd b66e35fc20e26204 353d28e566197766 92c64206254fe264 97514fc78b441504 f2117921aa735327 f21f20ec8e9379d5 f5ef96d58e4deb41 6958a1acae5243d3 71dd1ab5f9d7f109 2b2aedaf765a1e41 355cfd4e52502155 0094e33db6d14e63 6f0b690799f0c904 06203886dced107a a5c9d41a44ad8db7 a9aa88356aab8982 178a812c927f243b b9763c77cb542bf7 c275cf81ef010b80 -v 3   --numeric-times   ' returned non-zero exit status 1.
WARNING: Failed to query status of tasks on midway2: 
INFO: output:   /project2/mstephens/SuSIE_gtex_CPP/metasoft/gtex_metasoft_summary_stats/ENSG00000143318.12/ENSG00000143318.12.uniform.SuSiE_B.L_5.prior_0p1.res_var_false.rds /project2/mstephens/SuSIE_gtex_CPP/metasoft/gtex_metasoft_summary_stats/ENSG00000132681.16/ENSG00000132681.16.uniform.SuSiE_B.L_5.prior_0p1.res_var_false.rds... (35 items in 35 groups)
```

The highlight is the line 

```
FileNotFoundError: [Errno 2] No such file or directory: '/home/gaow/.sos/tasks/92c64206254fe264.sh'
ERROR: [Errno 2] No such file or directory: '/home/gaow/.sos/tasks/92c64206254fe264.sh'
```

**Comment by BoPeng** [comment]
Not sure if the patch works...

**Comment by gaow** [comment]
Not sure either ... does not seem a lot going on in between where the removal happens previously and now. I can test it but I'm keeping an SoS process running to wait for some feedback on #1149 . I can kill it and test this ticket (and others) after you decide if some information will be helpful to extract for #1149.

**Comment by BoPeng** [comment]
At least on my machine it fixes a case where a large number of touch jobs are created and re-submitted repeatedly. These are cases where the task engine and task executor compete for checking and changing task status....

**Comment by gaow** [comment]
I see, so you were able to reproduce the behavior and fix on your machine? That's good to know.

**Comment by BoPeng** [comment]
Not really but related. I fixed an issue where a task is being completed (with .pulse being removed) and reported as aborted or already running by another sos process. But the patch might also have fixed this issue.

**Comment by gaow** [comment]
Seems to work now. Will reopen otherwise.
