### ISSUE TITLE
local installation of sos and sos-notebook error

### ISSUE THREAD

**Issue by jma7** [vatlab/SoS#1184]
I got some error messages and can't see the kernel selections after local installation of sos and sos-notebook. 

Since I want development version of the code, what I did is inside conda:

1.   git clone sos, use ```pip install . -U ``` to install.
2.  git clone sos-notebook, run ```python setup install``` to install.
3.  run ```pip install sos-r```
4.  run ```python -m sos_notebook.install```
4.  run ``` jupyter kernelspec list```, shows

```
Available kernels:
  ir         /Users/jma7/Library/Jupyter/kernels/ir
  sos        /Users/jma7/Library/Jupyter/kernels/sos
  python3    /Users/jma7/anaconda/share/jupyter/kernels/python3
```

Start notebook:

```
(SOSenv) BSTMC07TP062G1J:sos_test jma7$ jupyter notebook
[I 10:45:03.784 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.4.1
[I 10:45:03.789 NotebookApp] Serving notebooks from local directory: /Users/jma7/Development/sos_test
[I 10:45:03.789 NotebookApp] 0 active kernels 
[I 10:45:03.789 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=738d884eafe514c4075a45d38eb8f95d557782c2ec1ef488
[I 10:45:03.789 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 10:45:03.794 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=738d884eafe514c4075a45d38eb8f95d557782c2ec1ef488
[I 10:45:04.573 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[I 10:45:08.283 NotebookApp] Creating new notebook in 
[I 10:45:09.001 NotebookApp] Kernel started: 727d12b0-72b8-4964-b41f-70e50b5ef961
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/Users/jma7/anaconda/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "/Users/jma7/anaconda/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/jma7/anaconda/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/Users/jma7/anaconda/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    self.pre_handler_hook()
  File "/Users/jma7/anaconda/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 248, in pre_handler_hook
    self.saved_sigint_handler = signal(SIGINT, default_int_handler)
  File "/Users/jma7/anaconda/lib/python3.6/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread
ERROR:tornado.general:Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "/Users/jma7/anaconda/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "/Users/jma7/anaconda/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/jma7/anaconda/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/Users/jma7/anaconda/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    self.pre_handler_hook()
  File "/Users/jma7/anaconda/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 248, in pre_handler_hook
    self.saved_sigint_handler = signal(SIGINT, default_int_handler)
  File "/Users/jma7/anaconda/lib/python3.6/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread

```

Any suggestions?

**Comment by BoPeng** [comment]
Can you use the R kernel by itself?

**Comment by BoPeng** [comment]
Note that `python setup install` is not supposed to be used because it will cause two separate installations with `pip install`. You should use `pip install sos-r` from pypi, or `pip install . -U` to install local master. If you have already done it, go to python package directory and remove all versions of sos-notebook.

**Comment by jma7** [comment]
Thanks, it is working now.
