### ISSUE TITLE
Keyword argument error `rebuild`

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1194]
The new release 0.18.3 broke a previously working pipeline, with error message:

```
  File "/scratch/midway2/gaow/miniconda3/lib/python3.6/site-packages/sos/__main__.py", line 402, in cmd_run
    executor.run(args.__targets__, mode='dryrun' if args.dryrun else 'run')
Traceback (most recent call last):
  File "/scratch/midway2/gaow/miniconda3/lib/python3.6/site-packages/sos/__main__.py", line 402, in cmd_run
    executor.run(args.__targets__, mode='dryrun' if args.dryrun else 'run')
  File "/scratch/midway2/gaow/miniconda3/lib/python3.6/site-packages/sos/workflow_executor.py", line 267, in run
    return self.run_as_master(targets=targets, mode=mode)
  File "/scratch/midway2/gaow/miniconda3/lib/python3.6/site-packages/sos/workflow_executor.py", line 1472, in run_as_master
    raise exec_error
  File "/scratch/midway2/gaow/miniconda3/lib/python3.6/site-packages/sos/workflow_executor.py", line 1306, in run_as_master
    raise exec_error
sos.workflow_executor.ExecuteError: [vhat_corshrink_xcondition (vhat_corshrin]: write() got an unexpected keyword argument 'rebuild'
```

Not sure if it is enough information to fix it from here? This bug is a bit embarrassing because it triggered removal of my previously completed computations. I cannot reproduce it easily with a MWE but I can try to do it if there is a need.

**Comment by BoPeng** [comment]
Sorry, I was pretty sure it was removed but perhaps I did not save the file before I commit. I have fixed the problem and released 0.18.4.

I will also add a test later.

**Comment by BoPeng** [comment]
https://github.com/vatlab/SoS/commit/36fb8b93c425ce5c0c64270ca117415a81ae6404

**Comment by gaow** [comment]
Great, thanks! The new release works well now.

**Comment by BoPeng** [comment]
This is why I have always been unsatisfied with our tests. The added tests are not very useful as they test a bug that has been already been fixed, but could help when I mess up with signatures next time.
