### ISSUE TITLE
Bug in executor code

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#1251]
The line in question is this:

https://github.com/vatlab/SoS/blob/8f15807dd7cf472e23003427d64a2e23d7059c8e/src/sos/step_executor.py#L717

The error message:

```
 File "/opt/miniconda3/lib/python3.6/site-packages/sos/step_executor.py", line 1616, in run
    yreq = runner.send(yres)
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.6/site-packages/sos/step_executor.py", line 1616, in run
    yreq = runner.send(yres)
  File "/opt/miniconda3/lib/python3.6/site-packages/sos/step_executor.py", line 1210, in run
    yreq = runner.send(yres)
  File "/opt/miniconda3/lib/python3.6/site-packages/sos/step_executor.py", line 717, in process_returned_substep_result
    self.proc_results[res['index']] = res
IndexError: list assignment index out of range
  File "/opt/miniconda3/lib/python3.6/site-packages/sos/__main__.py", line 413, in cmd_run
    executor.run(args.__targets__, mode='dryrun' if args.dryrun else 'run')
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.6/site-packages/sos/__main__.py", line 413, in cmd_run
    executor.run(args.__targets__, mode='dryrun' if args.dryrun else 'run')
  File "/opt/miniconda3/lib/python3.6/site-packages/sos/workflow_executor.py", line 322, in run
    return self.run_as_master(targets=targets, mode=mode)
  File "/opt/miniconda3/lib/python3.6/site-packages/sos/workflow_executor.py", line 1374, in run_as_master
    raise exec_error
  File "/opt/miniconda3/lib/python3.6/site-packages/sos/workflow_executor.py", line 1228, in run_as_master
    raise exec_error
sos.workflow_executor.ExecuteError: [76c0a754-7186-4cac-ac81-ce9810050f7d]: [twas]: list assignment index out of range
```

I can put together a MWE for this. @BoPeng do you need one?

**Comment by gaow** [comment]
Here is the MWE. To run it:

```
sos run test_index.sos -v3
```

there is actually another issue you can possibly reproduce with this one -- I got

```
  File "/opt/miniconda3/lib/python3.6/site-packages/sos/__main__.py", line 413, in cmd_run
    executor.run(args.__targets__, mode='dryrun' if args.dryrun else 'run')
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.6/site-packages/sos/__main__.py", line 413, in cmd_run
    executor.run(args.__targets__, mode='dryrun' if args.dryrun else 'run')
  File "/opt/miniconda3/lib/python3.6/site-packages/sos/workflow_executor.py", line 322, in run
    return self.run_as_master(targets=targets, mode=mode)
  File "/opt/miniconda3/lib/python3.6/site-packages/sos/workflow_executor.py", line 1374, in run_as_master
    raise exec_error
  File "/opt/miniconda3/lib/python3.6/site-packages/sos/workflow_executor.py", line 1228, in run_as_master
    raise exec_error
sos.workflow_executor.ExecuteError: [02598a37-2d7b-499c-b967-e0e25f24763b]: [nqual]: 'ret_code'
[test_index.tar.gz](https://github.com/vatlab/SoS/files/3070714/test_index.tar.gz)
```

Note that in this script the `depends` works. Is this because what contributes to `depends` here are in global?

Sorry for reporting many issues today ...

**Comment by BoPeng** [comment]
Ohmm, I can reproduce the bugs, not quite sure if it is related to line 711 because the patch looked quite innocent. Still checking.

**Comment by BoPeng** [comment]
But I have not been able to reproduce this in the last few runs.

**Comment by gaow** [comment]
On my end it always reproduces. Only sometimes one return code error, sometimes both errors.

**Comment by BoPeng** [comment]
Oh, I was running against a version with 711 reverted, only confirmed that 711 was causing the problem.

**Comment by BoPeng** [comment]
Well, the problem was with the context switching when multiple steps share the same process, and switch back and forth during the submission of substeps... I have a feeling that no one else would be able to understand and maintain the code. :-(

**Comment by gaow** [comment]
Thank you -- trying it out now. 

> I have a feeling that no one else would be able to understand and maintain the code. :-(

If there is no better solution, then perhaps add a reference to the issue number in the code comment?

**Comment by BoPeng** [comment]
> perhaps add a reference to the issue number in the code comment?

What I meant was that the  execution order of the code is quite complex now, and it is very difficult to figure out what went wrong from reading the code sequentially. What happened in this code was that some substeps are submitted in one context, and are received in another context, and the (incomplete) context switch was not at all obvious.
