### ISSUE TITLE
EOFError checking tasks status

### ISSUE THREAD

**Issue by gaow** [vatlab/sos#1275]
I now constantly run into this error message:

```
  File "/scratch/midway2/gaow/miniconda3/lib/python3.7/site-packages/sos/__main__.py", line 1360, in cmd_status
    status=args.status)
Traceback (most recent call last):
  File "/scratch/midway2/gaow/miniconda3/lib/python3.7/site-packages/sos/__main__.py", line 1360, in cmd_status
    status=args.status)
  File "/scratch/midway2/gaow/miniconda3/lib/python3.7/site-packages/sos/tasks.py", line 1114, in print_task_status
    raw_status = check_tasks([x[0] for x in all_tasks], check_all)
  File "/scratch/midway2/gaow/miniconda3/lib/python3.7/site-packages/sos/tasks.py", line 1030, in check_tasks
    status_cache = pickle.load(cache)
EOFError: Ran out of input
ERROR: Ran out of input
WARNING: Check output of sos status M8_504cc1498dce4f80 M8_99d7b46120d332dc M8_1027c507f69674c1 M8_6eb9e34aaea1cb7a M8_b08c9a9cf285f38d M8_e845dd272d7c72 ...
WARNING: Failed to query status of tasks on midway2_head: 
```
Not sure what I can do to help debugging it ... just reporting it here. Never have seen in the past.

**Comment by BoPeng** [comment]
This looks like a corrputed pickle task status cache. Could you try to remove `status_cache.pickle` from `~/.sos/tasks`? If this is the case, I will have to use a try/except catch to rebuild this cache.

**Comment by gaow** [comment]
The warning goes away after I removed the file. Maybe it is reasonable to add a try .. catch statement. Removing the file did not seem to have any impact on my workflow at all.

**Comment by BoPeng** [comment]
The cache will be re-created if missing.
