### ISSUE TITLE
Indentation error

### ISSUE THREAD

**Issue by minqiao** [vatlab/sos#1283]
I'm still getting this error when running on the latest github version. It looks like some code format issues:

```
$ sos run dsc/20190717_workflow.ipynb get_stats:1-4 -s build -v4
  File "/home/min/miniconda3/lib/python3.6/site-packages/sos/__main__.py", line 550, in cmd_run
    executor.run(args.__targets__, mode=config['run_mode'])
Traceback (most recent call last):
  File "/home/min/miniconda3/lib/python3.6/site-packages/sos/eval.py", line 61, in accessed_vars
    return get_accessed(ast.parse(statement, '<string>', 'exec'))
  File "/home/min/miniconda3/lib/python3.6/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<string>", line 2
    = sos_handle_parameter_('', str
    ^
IndentationError: unexpected indent

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/min/miniconda3/lib/python3.6/site-packages/sos/__main__.py", line 550, in cmd_run
    executor.run(args.__targets__, mode=config['run_mode'])
  File "/home/min/miniconda3/lib/python3.6/site-packages/sos/workflow_executor.py", line 340, in run
    return self.run_as_master(targets=targets, mode=mode)
  File "/home/min/miniconda3/lib/python3.6/site-packages/sos/workflow_executor.py", line 1136, in run_as_master
    dag = self.initialize_dag(targets=targets)
  File "/home/min/miniconda3/lib/python3.6/site-packages/sos/workflow_executor.py", line 821, in initialize_dag
    self.add_forward_workflow(dag, self.workflow.sections)
  File "/home/min/miniconda3/lib/python3.6/site-packages/sos/workflow_executor.py", line 691, in add_forward_workflow
    res = analyze_section(section, default_input=default_input)
RuntimeError: Failed to parse statement: #begin_parameter 
 = sos_handle_parameter_('', str
) #end_parameter 
 in exec mode
ERROR: Failed to parse statement: #begin_parameter 
 = sos_handle_parameter_('', str
) #end_parameter 
 in exec mode
```

**Comment by BoPeng** [comment]
Is dsc/20190717_workflow.ipynb available on github?

**Comment by minqiao** [comment]
The attached zip file is minimal working example: workflow and the data used.
The command: sos run 20190717_workflow.ipynb get_stats:1-4 -s build

[minimal_working_example.zip](https://github.com/vatlab/sos/files/3484114/minimal_working_example.zip)

**Comment by minqiao** [comment]
Hi Dr. Peng,

I edited the path of the workflow in minimal working example, so you can reproduce the error without any editing. Please find attached.

[minimal_working_example_v2.zip](https://github.com/vatlab/sos/files/3484330/minimal_working_example_v2.zip)

**Comment by BoPeng** [comment]
Looks like the problem is cased by this empty parameter specification

![image](https://user-images.githubusercontent.com/9889312/62748945-196ffc00-ba20-11e9-97a4-99694a7957da.png)

**Comment by minqiao** [comment]
Yes... It worked after delete the parameter. Thank you so much!

**Comment by BoPeng** [comment]
I added a patch to allow empty parameter line because the error message is confusing.
