### ISSUE TITLE
logging error for nested workflow

### ISSUE THREAD

**Issue by minqiao** [vatlab/sos#1366]
Hi Dr. Peng,

I run into the error below when I used sos nested workflow on Midway Compute Cluster. It happens occasionally and can't be reproduced.

```
INFO: Running logistic_bvsr_1: 
INFO: Running logistic_bvsr_1: 
INFO: Running logistic_bvsr_1: 
INFO: Running logistic_bvsr_1: 
INFO: Running logistic_bvsr_1: 
INFO: Running logistic_bvsr_1: 
INFO: Running logistic_bvsr_1: 
INFO: Running logistic_bvsr_1: 
INFO: Running logistic_bvsr_1: 
--- Logging error ---
WARNING: Check output of sbatch ~/.sos/tasks/M5_976e784ec992ac4e.sh failed: Command 'sbatch ~/.sos/tasks/M5_976e784ec992ac4e.sh' died with <Signals.SIGTERM: 15>.
ERROR: Failed to submit task M5_976e784ec992ac4e:

Traceback (most recent call last):
  File "/scratch/midway2/gaow/miniconda3/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "/scratch/midway2/gaow/miniconda3/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/scratch/midway2/gaow/miniconda3/lib/python3.7/logging/__init__.py", line 622, in format
    s = self.formatMessage(record)
  File "/scratch/midway2/gaow/miniconda3/lib/python3.7/logging/__init__.py", line 590, in formatMessage
    def formatMessage(self, record):
  File "/scratch/midway2/gaow/miniconda3/lib/python3.7/site-packages/sos/workers.py", line 23, in signal_handler
    raise ProcessKilled()
sos.utils.ProcessKilled
Call stack:
  File "/scratch/midway2/gaow/miniconda3/lib/python3.7/threading.py", line 885, in _bootstrap
    self._bootstrap_inner()
  File "/scratch/midway2/gaow/miniconda3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/scratch/midway2/gaow/miniconda3/lib/python3.7/site-packages/sos/controller.py", line 597, in run
    decode_msg(self.master_push_socket.recv()))
  File "/scratch/midway2/gaow/miniconda3/lib/python3.7/site-packages/sos/controller.py", line 272, in handle_master_push_msg
    self.workers.add_request(msg[0], msg[1])
  File "/scratch/midway2/gaow/miniconda3/lib/python3.7/site-packages/sos/workers.py", line 536, in add_request
    self.start_worker()
  File "/scratch/midway2/gaow/miniconda3/lib/python3.7/site-packages/sos/workers.py", line 662, in start_worker
    worker.start()
  File "/scratch/midway2/gaow/miniconda3/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/scratch/midway2/gaow/miniconda3/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/scratch/midway2/gaow/miniconda3/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/scratch/midway2/gaow/miniconda3/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/scratch/midway2/gaow/miniconda3/lib/python3.7/multiprocessing/popen_fork.py", line 74, in _launch
    code = process_obj._bootstrap()
  File "/scratch/midway2/gaow/miniconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/scratch/midway2/gaow/miniconda3/lib/python3.7/site-packages/sos/workers.py", line 286, in run
    name=self._name_of_work(reply)).run_until_waiting()
  File "/scratch/midway2/gaow/miniconda3/lib/python3.7/site-packages/sos/workers.py", line 51, in run_until_waiting
    self._poller = next(self._runner)
  File "/scratch/midway2/gaow/miniconda3/lib/python3.7/site-packages/sos/workers.py", line 368, in run_workflow
    yreq = next(runner)
  File "/scratch/midway2/gaow/miniconda3/lib/python3.7/site-packages/sos/workflow_executor.py", line 1693, in run_as_nested
    dag = self.initialize_dag(targets=targets)
  File "/scratch/midway2/gaow/miniconda3/lib/python3.7/site-packages/sos/workflow_executor.py", line 824, in initialize_dag
    dag.build()
  File "/scratch/midway2/gaow/miniconda3/lib/python3.7/site-packages/sos/dag.py", line 341, in build
    env.log_to_file('DAG', 'build DAG')
  File "/scratch/midway2/gaow/miniconda3/lib/python3.7/site-packages/sos/utils.py", line 379, in log_to_file
    self.logger.debug(topic + ' - ' + str(msg))
Message: 'DAG - build DAG'
Arguments: ()
INFO: M5_8e2451c26fb2e826 submitted to midway2 with job id 631035
INFO: M5_1f8dd2aeb1230fed submitted to midway2 with job id 631038
INFO: M5_8c29d57fa29caa48 submitted to midway2 with job id 631039
INFO: M5_6631bef2bf68d797 submitted to midway2 with job id 631040
INFO: M5_91f0a69caed74d9f submitted to midway2 with job id 631041
INFO: M5_69f58c0aa0fe4cc8 submitted to midway2 with job id 631042
INFO: M5_f5065fbbd827c47d submitted to midway2 with job id 631046
ERROR: [pymc3]: Too many open files
[pymc3]: Exits with 1 pending step (pymc3_4)
INFO: M5_4662f312defc8c82 submitted to midway2 with job id 631048
INFO: M5_a9d151ff37d67a0c submitted to midway2 with job id 631049
INFO: M5_775c8893ca5bb1ce submitted to midway2 with job id 631050
INFO: M5_279e22c2bdf05e46 submitted to midway2 with job id 631051
```

**Comment by BoPeng** [comment]
Too many open files is something difficult to debug or fix. Basically this means the total number of used files exceeds system allocation, which could be due to sos, or something else that uses too many file handles. Reducing `-j` would help.

The only way to debug this is to check the number of files (using command `lsof`) belong to sos processes when this happens.

**Comment by BoPeng** [comment]
#1376
