### ISSUE TITLE
corrupted task file causing sos status to fail

### ISSUE THREAD

**Issue by BoPeng** [vatlab/sos#1433]
For whatever reason the task file is corrupted, but this should not prevent the `sos status` file from finishing.

```
$ sos status -s running
ERROR: Failed to obtain params of task t5t0f7a8744b70ae2:

$ sos status -s running -v3
  File "/home/u233771/.local/lib/python3.7/site-packages/sos/__main__.py", line 1670, in cmd_status
    status=args.status,
Traceback (most recent call last):
  File "/home/u233771/.local/lib/python3.7/site-packages/sos/tasks.py", line 701, in _get_params
    return pickle.loads(lzma.decompress(fh.read(header.params_size)))
  File "/share/apps/anaconda3/2019.10/lib/python3.7/lzma.py", line 334, in decompress
    res = decomp.decompress(data)
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/u233771/.local/lib/python3.7/site-packages/sos/__main__.py", line 1670, in cmd_status
    status=args.status,
  File "/home/u233771/.local/lib/python3.7/site-packages/sos/tasks.py", line 1451, in print_task_status
    raw_status = check_tasks([x[0] for x in all_tasks], check_all)
  File "/home/u233771/.local/lib/python3.7/site-packages/sos/tasks.py", line 1372, in check_tasks
    raw_status = p.starmap(check_task, [(x, status_cache.get(x, {})) for x in tasks])
  File "/share/apps/anaconda3/2019.10/lib/python3.7/multiprocessing/pool.py", line 276, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "/share/apps/anaconda3/2019.10/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
RuntimeError: Failed to obtain params of task t5t865abef6f277f7:
ERROR: Failed to obtain params of task t5t865abef6f277f7:
```

**Comment by BoPeng** [comment]
It is very weird. The task file is not corrupted and everytime the error would be raised from a different task....

**Comment by BoPeng** [comment]
Somehow it was caused by too many threads that are checking the status of tasks.
