### ISSUE TITLE
Undefined base function error

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#370]
I cannot find a MWE for this one but maybe the error message is good enough?

```
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.0-py3.5.egg/sos/sos_step.py", line 1078, in run
    res = Base_Step_Executor.run(self)
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.0-py3.5.egg/sos/sos_step.py", line 1078, in run
    res = Base_Step_Executor.run(self)
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.0-py3.5.egg/sos/sos_step.py", line 959, in run
    env.sos_dict['_local_output_{}'.format(idx)])
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.0-py3.5.egg/sos/target.py", line 499, in write
    f.write_sig()
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.0-py3.5.egg/sos/target.py", line 139, in write_sig
    sig.write('{}\t{}\n'.format(self.name(), self.signature()))
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.0-py3.5.egg/sos/target.py", line 120, in signature
    raise RuntimeError('Undefined base function')
RuntimeError: Undefined base function
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.0-py3.5.egg/sos/__main__.py", line 302, in cmd_run
    executor.run(args.__targets__)
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.0-py3.5.egg/sos/__main__.py", line 302, in cmd_run
    executor.run(args.__targets__)
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.0-py3.5.egg/sos/sos_executor.py", line 817, in run
    raise exec_error
sos.sos_executor.ExecuteError: Failed to execute workflow aim
[aim_1] RuntimeError:
	Undefined base function
```

So it looks like somehow `f.write_sig` is a base class function for my workflow. I am out of town and debugging from terminal I did not fix the issue. I'm yet to copy files over to my laptop and test ... but maybe it is something obvious?

**Comment by BoPeng** [comment]
It seems that your `output` parameter for some option that is not a string (file name). What is the relevant (or full) code?

**Comment by gaow** [comment]
I am not sure ... here is the relevant code that fails by itself:

```
parameter: resource_dir = "/home/gaow/Documents/MultiSeq"
parameter: ped = "Blood_48k_pub.ped"

[aim_1: shared = {'vcf2rds_output': 'output'}]
# Convert VCF data to one RDS matrix
depends: R_library("gaow/vcfR")
input: glob.glob(os.path.join(resource_dir, "*_chr*.vcf.gz"))
output: os.path.join(resource_dir, ped[:-4] + '.rds')
R: workdir=resource_dir
  library(vcfR)
  input <- c(${input!r,})
  for (i in 1:length(input)) {
      vcf <- read.vcfR(input[i], verbose = FALSE)
      mat <- t(extract.gt(vcf, as.numeric = T))
      colnames(mat) <- read.table(pipe(paste("zcat", input[i], "| grep -v '^#' | cut -f 3")), as.is = T)[,1]
      if (i == 1) {
         res <- mat
      } else {
         tmp <- merge(res, mat, by = 0)
         res <- tmp[,-1]
         rownames(res) <- tmp[,1]
      }
      cat(paste(input[i], "processed!\n"))
  }
  saveRDS(res, ${output!r})

```

Here is an attempt to make a MWE on my laptop. But it works!

```
parameter: resource_dir = "/home/gaow/Desktop"
parameter: ped = "test.ped"

[test_1: shared = {'test_out': 'output'}]
input: glob.glob(os.path.join(resource_dir, '*.vcf.gz'))
output: os.path.join(resource_dir, ped[:-4] + '.rds')
R: workdir = 'resource_dir'
 system("touch ${output}")
```

**Comment by BoPeng** [comment]
Cannot reproduce (no `.vcf.gz` file), could you print what is `f` at 

```
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.0-py3.5.egg/sos/target.py", line 499, in write
    f.write_sig()
```

**Comment by gaow** [comment]
Good call! Found the culprit -- it is `R_library` and here is the MWE:

```
[default]
depends: R_library("gaow/vcfR")
input: '1.txt'
output: '2.txt'
R:
 system("touch ${output}")
```

**Comment by BoPeng** [comment]
I see. The `R_library` was not updated with the base class update and lacks a `signature` function. I am fixing it.

**Comment by BoPeng** [comment]
```
diff --git a/sos/R/target.py b/sos/R/target.py
index 58efefb..b216644 100644
--- a/sos/R/target.py
+++ b/sos/R/target.py
@@ -171,6 +171,6 @@ class R_library(BaseTarget):
     def name(self):
         return self._library

-    def md5(self):
+    def signature(self):
         # we are supposed to get signature of the library, but we cannot
         return textMD5(repr(self._library))
```

check if this works and commit.

**Comment by BoPeng** [comment]
The same to `Py_Module` in `sos/Python/target.py`

**Comment by gaow** [comment]
Yes it does work! I patched both.
