### ISSUE TITLE
Nested workflow error message does not show properly

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#396]
Here is the MWE:

```
[test_1]
R:
  set.seed(xxx)

[default]
sos_run('test')
```

and it gives long ugly output without highlighting the error in red, and I have to use keyboard to kill it:

```
[GW] sos run test3.sos 
INFO: Executing default_0: 
INFO: default_0 input:    []
INFO: Executing workflow test with input []
INFO: Executing test_1: 
INFO: test_1 input:    []
Error in set.seed(xxx) : object 'xxx' not found
Execution halted
Process Process-1:1:
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/opt/miniconda3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.0-py3.5.egg/sos/sos_executor.py", line 817, in run
    raise exec_error
sos.sos_executor.ExecuteError: Failed to execute workflow test
[test_1] RuntimeError:
	Failed to process statement 'R(r"""set.seed(xxx)\n\n""")\n': Failed to execute script (ret=1). 
Please use command
    Rscript --default-packages=datasets,methods,utils,stats,grDevices,graphics  /home/gaow/GIT/github/dsc2-omega/dsc2/.sos/test_1_0.R
under /home/gaow/GIT/github/dsc2-omega/dsc2 to test it.
[test] RuntimeError:
	1 failed step: test_1
^CTraceback (most recent call last):
  File "/opt/miniconda3/bin/sos", line 11, in <module>
    load_entry_point('sos==0.9.0', 'console_scripts', 'sos')()
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.0-py3.5.egg/sos/__main__.py", line 1226, in main
Process Process-1:
    args.func(args, workflow_args)
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.0-py3.5.egg/sos/__main__.py", line 302, in cmd_run
    executor.run(args.__targets__)
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.0-py3.5.egg/sos/sos_executor.py", line 803, in run
    time.sleep(0.1)
KeyboardInterrupt
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/opt/miniconda3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.0-py3.5.egg/sos/sos_step.py", line 1078, in run
    res = Base_Step_Executor.run(self)
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.0-py3.5.egg/sos/sos_step.py", line 941, in run
    self.execute(statement[1], signatures[idx])
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.0-py3.5.egg/sos/sos_step.py", line 661, in execute
    self.last_res = SoS_exec(stmt, self.step.sigil)
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.0-py3.5.egg/sos/sos_eval.py", line 473, in SoS_exec
    res = eval(stmts, _dict)
  File "<string>", line 1, in <module>
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.0-py3.5.egg/sos/actions.py", line 150, in action_wrapper
    res = func(*args, **kwargs)
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.0-py3.5.egg/sos/actions.py", line 330, in sos_run
    res = q.get()
  File "/opt/miniconda3/lib/python3.5/multiprocessing/queues.py", line 94, in get
    res = self._recv_bytes()
  File "/opt/miniconda3/lib/python3.5/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/opt/miniconda3/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/opt/miniconda3/lib/python3.5/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
```

However if I do not run the nested workflow the output is nice and clear:

```
[GW] sos run test3.sos test
INFO: Executing test_1: 
INFO: test_1 input:    []
Error in set.seed(xxx) : object 'xxx' not found
Execution halted
ERROR: Failed to execute workflow test
[test_1] RuntimeError:
	Failed to process statement 'R(r"""set.seed(xxx)\n\n""")\n': Failed to execute script (ret=1). 
Please use command
    Rscript --default-packages=datasets,methods,utils,stats,grDevices,graphics  /home/gaow/GIT/github/dsc2-omega/dsc2/.sos/test_1_0.R
under /home/gaow/GIT/github/dsc2-omega/dsc2 to test it.
[test] RuntimeError:
	1 failed step: test_1
```

**Comment by BoPeng** [comment]
This is because all subworkflows are now executed in a separate process (this is related to #349), and, without a proper way to pass the exception to the main process, the main process will just hang.

A mechanism similar to how step-executor passes exception to workflow executor should be used. I will get to this later this week.

**Comment by gaow** [comment]
I'm running into this interesting observation which I think at one point we have dealt with. It is issue with large config files. Now for this same test:

```
[test_1]
R:
  set.seed(xxx)

[default]
sos_run('test')
```

The patch fixes the issue. However with a large config file it hangs:
```
[GW] sos run test.sos -c test.conf 
INFO: Executing default_0: 
INFO: default_0 input:    []
INFO: Executing workflow test with input []
INFO: Executing test_1: 
INFO: test_1 input:    []
Error in set.seed(xxx) : object 'xxx' not found
Execution halted


```

even though the conf file does not do anything! Here is the config file for test. 
[test.conf.txt](https://github.com/vatlab/SOS/files/748939/test.conf.txt)

**Comment by BoPeng** [comment]
This is very strange and I could not figure out what is going on after 30 minutes. The single process case works (-j4), but this involves 4 processes for master, 4 processes for nested, and a bunch of pipes connecting them...

**Comment by BoPeng** [comment]
The patch uses single-process to handle nested workflows and works here. Using multiple processes is wrong anyway because the total number of processes would exceed the specified jobs. A proper solution would be sharing a worker pool for both master and nested workflows....

**Comment by gaow** [comment]
But then we'll not have multi-processing with nested workflow, which is a disaster ...

**Comment by gaow** [comment]
Also I should add that if you use a shorter CONF then there is no problem. I recall last time we had the similar problem and the reason was the CONF dict has random order and it gets different every time when CONF is large (small CONF perhaps can only have limited random ordering). Not sure if this problem is of similar nature.

**Comment by BoPeng** [comment]
Well, consider this as a temporary fix. I suspect that what was happening was that when an error happened, the step process that execute sos_run is killed but some processes from the nested workflow are still alive. A lot more care is needed to really get all the process/pipe working correctly when errors happens.

**Comment by BoPeng** [comment]
Ok, there is also a possibility of race condition when multiple processes tries to read the same config file... Let me check this end.

**Comment by gaow** [comment]
> Ok, there is also a possibility of race condition when multiple processes tries to read the same config file... Let me check this end.

Sound promising -- larger CONF takes longer to read thus the race!

> A lot more care is needed to really get all the process/pipe working correctly when errors happens.

Is it more advantageous to use asycio then?

**Comment by BoPeng** [comment]
The problem was with the pickling of this large `frozendict` through pipes. I will see how to fix it.
