### ISSUE TITLE
Configuration file path issue

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#415]
I have a nested workflow complaining configuration file not found:

```
Process Process-1:1:
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/opt/miniconda3/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.4-py3.5.egg/sos/sos_executor.py", line 671, in run
    self.reset_dict()
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.4-py3.5.egg/sos/sos_executor.py", line 186, in reset_dict
    raise RuntimeError('Config file {} not found'.format(self.config['config_file']))
RuntimeError: Config file configuration.conf not found

```

It was not easy to make a MWE but this patch works for me:

```
diff --git a/sos/__main__.py b/sos/__main__.py
index 7e1ec34..21dbed9 100755
--- a/sos/__main__.py
+++ b/sos/__main__.py
@@ -291,7 +291,8 @@ def cmd_run(args, workflow_args):
         script = SoS_Script(filename=args.script)
         workflow = script.workflow(args.workflow, use_default=not args.__targets__)
         executor = executor_class(workflow, args=workflow_args, config={
-                'config_file': args.__config__,
+                'config_file': os.path.abspath(os.path.expanduser(args.__config__))
+                                               if args.__config__ else None,
                 'output_dag': args.__dag__,
                 'report_output': args.__report__})
         #
```

Is this patch good to commit, or shall I do it in `BaseExecutor`?

**Comment by BoPeng** [comment]
Doing it in base executor when `__config_file__` is defined seems to be better.

**Comment by gaow** [comment]
How about now:
```diff
diff --git a/sos/sos_executor.py b/sos/sos_executor.py
index 330115b..08e730a 100755
--- a/sos/sos_executor.py
+++ b/sos/sos_executor.py
@@ -87,6 +87,8 @@ class Base_Executor:
         for key in ('config_file', 'output_dag', 'report_output'):
             if key not in self.config:
                 self.config[key] = None
+        if self.config['config_file'] is not None:
+            self.config['config_file'] = os.path.abspath(os.path.expanduser(self.config['config_file']))
         # if the executor is not called from command line, without sigmode setting
         if env.sig_mode is None:
             env.sig_mode = 'default'
```

**Comment by BoPeng** [comment]
Ok, I was thinking of changing lines around `__config_file__ = self.config['config_file']`, but yours would also work. Please commit.
