### ISSUE TITLE
Attribute error `DupFd`

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#493]
I cannot reproduce this problem because the 2nd time I execute it is gone ... so hopefully it's possible to "blind debug" the attribute error here:

```
Process SoS_Worker-3:
Process SoS_Worker-4:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/opt/miniconda3/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.4-py3.5.egg/sos/sos_executor.py", line 125, in run
    work = self.queue.get()
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.4-py3.5.egg/sos/sos_executor.py", line 125, in run
    work = self.queue.get()
  File "/opt/miniconda3/lib/python3.5/multiprocessing/queues.py", line 113, in get
    return ForkingPickler.loads(res)
  File "/opt/miniconda3/lib/python3.5/multiprocessing/queues.py", line 113, in get
    return ForkingPickler.loads(res)
AttributeError: Can't get attribute 'DupFd' on <module 'multiprocessing.resource_sharer' from '/opt/miniconda3/lib/python3.5/multiprocessing/resource_sharer.py'>
AttributeError: Can't get attribute 'DupFd' on <module 'multiprocessing.resource_sharer' from '/opt/miniconda3/lib/python3.5/multiprocessing/resource_sharer.py'>

^CProcess SoS_Worker-5:
Process SoS_Worker-7:
Process SoS_Worker-2:
Process SoS_Worker-8:
Process SoS_Worker-6:
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.4-py3.5.egg/sos/sos_executor.py", line 125, in run
    work = self.queue.get()
  File "/opt/miniconda3/lib/python3.5/multiprocessing/queues.py", line 94, in get
    res = self._recv_bytes()
  File "/opt/miniconda3/lib/python3.5/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/opt/miniconda3/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/opt/miniconda3/lib/python3.5/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
....
```

**Comment by gaow** [comment]
It is interesting a search for `DupFd` in the SoS code resulted in no match ....

**Comment by BoPeng** [comment]
Might match https://github.com/vatlab/SOS/blob/master/sos/hosts.py#L99

Basically the online recipes have those but I commented them out because I did not understand what they are doing.

**Comment by gaow** [comment]
It's just weird that my 2nd run was fine, so I cannot reproduce it!

**Comment by BoPeng** [comment]
You can read http://stackoverflow.com/questions/881388/what-is-the-reason-for-performing-a-double-fork-when-creating-a-daemon and see if the error is expected without `dup2`.

**Comment by gaow** [comment]
From reading the text it looks like creating a double-fork prevents the daemon from accessing non-existent "session leader". But still I cannot reproduce the problem so it's hard to tell ... I think I'll see how often it recurs, if at all, then try to change that line of code to see if it fix the issue.

**Comment by gaow** [comment]
At least I can now confirm that after uncommenting those lines I can still run into the issues. I'm not sure why I cannot reproduce it. It seems to come back after I kill all the jobs (`killall sos; killall python`) and restart SoS. But still I cannot reproduce it every time. Will try some more and report back when I get a pattern.

**Comment by BoPeng** [comment]
Are you running tasks locally? If so, try to modify https://github.com/vatlab/SOS/blob/master/sos/hosts.py#L130 and use `subprocess.Popen(cmd, shell=True)` directly and not using `DaemonizedProcess` to make sure this is not the culprit.

**Comment by gaow** [comment]
Well it does not look like a problem for extern task. Rather it's the non-extern task part that runs into the error, because my patch is:

```diff
         # run command but does not wait for result.
-        if env.run_mode == 'dryrun':
+        # if env.run_mode == 'dryrun':
+        if 1:
+            print('no daemon')
```
But it does not even show me the line `no daemon` before it crashes. This is very useful information. I'll see if I can eventually reproduce it via non-task steps.

**Comment by BoPeng** [comment]
I am getting this error now but cannot seem to find its source...

**Comment by BoPeng** [comment]
Sometimes the error appears as

```
DEBUG: Worker working on a step with args []
Traceback (most recent call last):
  File "/Users/bpeng1/anaconda/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/Users/bpeng1/anaconda/lib/python3.6/site-packages/sos-0.9.4-py3.6.egg/sos/sos_executor.py", line 137, in run
    work = self.cmd_queue.get()
  File "/Users/bpeng1/anaconda/lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File "/Users/bpeng1/anaconda/lib/python3.6/multiprocessing/connection.py", line 951, in rebuild_connection
    fd = df.detach()
  File "/Users/bpeng1/anaconda/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/Users/bpeng1/anaconda/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/Users/bpeng1/anaconda/lib/python3.6/multiprocessing/connection.py", line 487, in Client
    c = SocketClient(address)
  File "/Users/bpeng1/anaconda/lib/python3.6/multiprocessing/connection.py", line 614, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 61] Connection refused
```

so there must be some deep rooted race condition stuff.

**Comment by BoPeng** [comment]
OK, the source of the problem is still unclear but the patch can hopefully fix the bug.

What the `spawn` mode means is that `SoS_Worker` will start from completely new process. In comparison the default `fork` mode will fork a process from the current process so it is likely that some resource are shared by two processes whereas they are not supposed to be shared.

The `spawn` mode is slower than `fork` so we might re-visit this bug if we know exactly what resource has caused the problem and share it properly between `SoS_Worker`.
