### ISSUE TITLE
`SoS_Worker` indexing bug

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#569]
I'm running into this issue as part of error message of a failed step in my pipeline. I'm posting this part only, because I think it is problem on the SoS end:

```
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.4-py3.5.egg/sos/sos_step.py", line 1213, in run
    res = Base_Step_Executor.run(self)
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.4-py3.5.egg/sos/sos_step.py", line 1213, in run
    res = Base_Step_Executor.run(self)
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.4-py3.5.egg/sos/sos_step.py", line 1064, in run
    self.wait_for_results()
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.4-py3.5.egg/sos/sos_step.py", line 667, in wait_for_results
    self.proc_results[idx] = results[task]
TypeError: 'NoneType' object is not subscriptable
DEBUG: Worker 1 completes request step
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.4-py3.5.egg/sos/sos_step.py", line 1213, in run
    res = Base_Step_Executor.run(self)
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.4-py3.5.egg/sos/sos_step.py", line 706, in execute
    self.last_res = SoS_exec(stmt, self.step.sigil)
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.4-py3.5.egg/sos/sos_eval.py", line 488, in SoS_exec
    res = eval(stmts, _dict)
  File "<string>", line 6, in <module>
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.4-py3.5.egg/sos/actions.py", line 144, in action_wrapper
    res = func(*args, **kwargs)
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.4-py3.5.egg/sos/actions.py", line 357, in sos_run
    env.sos_dict.quick_update(res['shared'])
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.4-py3.5.egg/sos/sos_step.py", line 1213, in run
    res = Base_Step_Executor.run(self)
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.4-py3.5.egg/sos/sos_step.py", line 1004, in run
    self.execute(statement[1], signatures[idx])
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.4-py3.5.egg/sos/sos_step.py", line 716, in execute
    raise RuntimeError('Failed to process statement {} ({}): {}'.format(short_repr(stmt), e.__class__.__name__, e))
RuntimeError: Failed to process statement sos_run('FM.fr_to_plink + FM.p...vised')\n\n\n (TypeError): 'NoneType' object is not subscriptable
DEBUG: Worker 1 completes request step
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.4-py3.5.egg/sos/__main__.py", line 310, in cmd_run
    executor.run(args.__targets__, mode='dryrun' if args.__dryrun__ else 'run')
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.4-py3.5.egg/sos/sos_executor.py", line 868, in run
    len([x for x in res if x=='aborted']), len([x for x in res if x=='result-mismatch']) ))
RuntimeError: 0 completed, 1 failed, 0 aborted, 0 mismatch

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.4-py3.5.egg/sos/__main__.py", line 310, in cmd_run
    executor.run(args.__targets__, mode='dryrun' if args.__dryrun__ else 'run')
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.4-py3.5.egg/sos/sos_executor.py", line 1002, in run
    p[0].terminate()
TypeError: 'SoS_Worker' object does not support indexing
ERROR: 'SoS_Worker' object does not support indexing
TRACE: Killing 8342 and all its children
DEBUG: Failed to clean up running process: psutil.NoSuchProcess no process found with pid 8342
```

**Comment by BoPeng** [comment]
The last two messages are from the cleanup code that I removed yesterday... did you use the latest master?

**Comment by BoPeng** [comment]
If you run with `-v3`, even `-v4`, it should show what the master process is doing, which should help my debug. In particular, the worker should have sent a list of tasks to the master but got incorrect response.

**Comment by gaow** [comment]
I was running latest version and that message was from `-v4`. The bug is easy to reproduce, though:

```
[1]
task:
R:
 asdf
```

and it will show the error.

**Comment by BoPeng** [comment]
The master process exited without sending results to worker when a task fails ....
