### ISSUE TITLE
Error handling with `check_output` in remote task submissions

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#601]
This is separated from  #598 

So with the new raise behavior I do end up hitting errors now, but there are side effects as expected:

```
TRACE: Step becomes task_pending
TRACE: Start submitting 9bd00f38d7e11b17d9638e31a6a487bf (status: pending)
ERROR: Task 9bd00f38d7e11b17d9638e31a6a487bf requested more walltime (20000:00:00) than allowed max_walltime (36:00:00)
WARNING: 9bd00f38d7e11b17d9638e31a6a487bf failed
DEBUG: scp -P 22 -p -q gaow@midway.rcc.uchicago.edu:.sos/tasks/9bd00f38d7e11b17d9638e31a6a487bf.* /home/gaow/.sos/tasks
  File "/opt/miniconda3/lib/python3.6/site-packages/sos-0.9.4-py3.6.egg/sos/__main__.py", line 306, in cmd_run
    executor.run(args.__targets__, mode='dryrun' if args.dryrun else 'run')
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.6/site-packages/sos-0.9.4-py3.6.egg/sos/__main__.py", line 306, in cmd_run
    executor.run(args.__targets__, mode='dryrun' if args.dryrun else 'run')
  File "/opt/miniconda3/lib/python3.6/site-packages/sos-0.9.4-py3.6.egg/sos/sos_executor.py", line 1004, in run
    raise e
  File "/opt/miniconda3/lib/python3.6/site-packages/sos-0.9.4-py3.6.egg/sos/sos_executor.py", line 864, in run
    task_status = proc[2]._host.retrieve_results(proc[2]._pending_tasks)
  File "/opt/miniconda3/lib/python3.6/site-packages/sos-0.9.4-py3.6.egg/sos/hosts.py", line 746, in retrieve_results
    return {task: self._host_agent.receive_result(task) for task in tasks}
  File "/opt/miniconda3/lib/python3.6/site-packages/sos-0.9.4-py3.6.egg/sos/hosts.py", line 746, in <dictcomp>
    return {task: self._host_agent.receive_result(task) for task in tasks}
FileNotFoundError: [Errno 2] No such file or directory: '/home/gaow/.sos/tasks/9bd00f38d7e11b17d9638e31a6a487bf.res'
ERROR: [Errno 2] No such file or directory: '/home/gaow/.sos/tasks/9bd00f38d7e11b17d9638e31a6a487bf.res'
```

**Comment by BoPeng** [comment]
Try again. Hopefully there are not many individual errors like this to handle.

**Comment by gaow** [comment]
It is fixed! I'll keep an eye of other possible issues. Thanks a lot!
