### ISSUE TITLE
iJavaScript kernel fail to start on TravisCI

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#644]
`ijsinstall` did not return any error message, not sure why `ijskernel` could not start, perhaps missing package.

**Comment by BoPeng** [comment]
The error message from `iJavaScript` itself is 
```
>           self.assertEqual(stderr, '', 'Got error message {}'.format(stderr))
E           AssertionError: 'Failed to start kernel "JavaScript". Use [849 chars]fo\n' != ''
E           Diff is 913 characters long. Set self.maxDiff to None to see it. : Got error message Failed to start kernel "JavaScript". Use "jupyter kernelspec list" to check if it is installed: Failed to start javascript: stdout: 
E            stderr: module.js:598
E             return process.dlopen(module, path._makeLong(filename));
E                            ^
E           
E           Error: Module did not self-register.
E               at Object.Module._extensions..node (module.js:598:18)
E               at Module.load (module.js:488:32)
E               at tryModuleLoad (module.js:447:12)
E               at Function.Module._load (module.js:439:3)
E               at Module.require (module.js:498:17)
E               at require (internal/module.js:20:19)
E               at Object.<anonymous> (/usr/local/lib/node_modules/ijavascript/node_modules/jp-kernel/node_modules/jmp/node_modules/zeromq/lib/index.js:6:11)
E               at Module._compile (module.js:571:32)
E               at Object.Module._extensions..js (module.js:580:10)
E               at Module.load (module.js:488:32)
E           
E            exception: Kernel died before replying to kernel_info
```

This is a well known problem caused by incomplete removal of nodejs, so we will have to thoroughly remove nodejs before installing `nodejs-ledacy`.

**Comment by BoPeng** [comment]
Finally, removing `~/.nvm` worked. It took me a long time to figure this out but the error reporting of cases like this has been improved a lot.
