### ISSUE TITLE
SAS over saspy on Mac

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#680]
With a configuration of
```
SAS_config_names=['ssh']
SAS_config_options = {'lock_down': True}
ssh      = {' ...
```
I am getting 
```
>>> import os
>>> sas = saspy.SASsession()
Using SAS Config named: ssh
Exception ignored in: <bound method SASsessionSTDIO.__del__ of <saspy.sasiostdio.SASsessionSTDIO object at 0x101c35470>>
Traceback (most recent call last):
  File "/Users/bpeng1/anaconda/lib/python3.5/site-packages/saspy/sasiostdio.py", line 157, in __del__
    self._endsas()
  File "/Users/bpeng1/anaconda/lib/python3.5/site-packages/saspy/sasiostdio.py", line 280, in _endsas
    self._getlog(wait=1)
  File "/Users/bpeng1/anaconda/lib/python3.5/site-packages/saspy/sasiostdio.py", line 313, in _getlog
    rc = os.waitid(os.P_PID, self.pid, os.WEXITED | os.WNOHANG)
AttributeError: module 'os' has no attribute 'waitid'
Exception ignored in: <object repr() failed>
```

And it appears that `os.waitid` is [unavailable for mac](https://bugs.python.org/issue10812).

This is not SoS' problem but makes it difficult for it to work with SAS.

**Comment by BoPeng** [comment]
From the doc: https://sassoftware.github.io/sas_kernel/install.html

    For OSX, the only supported configuration is an IOM connection.

In my particular case,

1. Figure out the location of configuration file using
    ```
    python -c 'import saspy;print(saspy.SAScfg)'
    ```
    which is something like `/Users/bpeng1/anaconda/lib/python3.5/site-packages/saspy/sascfg.py` for anaconda python3.

2. Log on to the remote server and find the SAS Deployment Manger Java Files, where are located at somewhere like `/usr/local/data/SASHome/SASDeploymentManager/9.3/products/deploywiz__93540__prt__xx__sp0__1/deploywiz/`, **copy the files to the local machine**, then modify the cfg file with something like:

```
SAS_config_names=['iom']

SAS_config_options = {'lock_down': True}

cpL  =  "/path/to/sas.svc.connection.jar"
cpL += ":/path/to/log4j.jar"
cpL += ":/path/to/sas.security.sspi.jar"
cpL += ":/path/to/sas.core.jar"
cpL += ":/Users/bpeng1/anaconda/lib/python3.5/site-packages/saspy/java/saspyiom.jar"

iom = {'java'  : '/usr/bin/java',
            'iomhost'   : 'linux_server_URL',
            'iomport'   : 8591,
            'encoding'  : 'latin1',
            'classpath' : cpL,
           'authkey': 'linux_server',
            }           
```

3. Create an authkey file (e.g. `~/.authkey`) with username and password
    ```
    linux_server  user XXX password XXXX
     ```
4. Test the configuration file with command

    ```
    python -c 'import saspy;saspy.SASsession()'
    ```

You will see something like "SAS Connection failed.". This is where we need to start the SAS server from the server, which is explained [here](http://support.sas.com/rnd/itech/doc9/admin_oma/sasserver/startserv/sp_suunx.html).

**Comment by BoPeng** [comment]
`saspy` does not support mac as far as I can tell.
