### ISSUE TITLE
Improper error message when missing input file

### ISSUE THREAD

**Issue by gaow** [vatlab/SOS#720]
One can use the same example as in #719 but without input file `1.txt` present. Then this is what happens:

```
sos run test.sos 
INFO: Executing default_1: 
INFO: Resolving 1 objects from 1 nodes
ERROR: 'NoneType' object is not iterable
^CProcess SoS_Worker-1:
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.5/multiprocessing/popen_fork.py", line 29, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.8.8-py3.5.egg/sos/sos_executor.py", line 142, in run
    work = self.pipe.recv()
  File "/opt/miniconda3/lib/python3.5/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/opt/miniconda3/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/opt/miniconda3/lib/python3.5/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
```
It hangs on that line of non-informative error message complaining about `None type`

**Comment by BoPeng** [comment]
I see

```
$ sos run test
INFO: Executing default_1:
INFO: input:    ['1.txt']
INFO: 477253501b417cca28671b014776ad3a queued
INFO: 477253501b417cca28671b014776ad3a started
ERROR: 477253501b417cca28671b014776ad3a failed with UnknownTarget error Target unavailable: 1.txt
WARNING: 477253501b417cca28671b014776ad3a failed
INFO: 477253501b417cca28671b014776ad3a.err:
2017-07-24 15:08:43,171: INFO: 477253501b417cca28671b014776ad3a ``started``
2017-07-24 15:08:43,187: ERROR: 477253501b417cca28671b014776ad3a ``failed`` with UnknownTarget error Target unavailable: 1.txt
sos execute quits with code 1 and exception UnknownTarget: Target unavailable: 1.txt

ERROR: 1 job failed
```
Perhaps you need to pull and compile?

**Comment by gaow** [comment]
Hmm I did pull and compile but still get this error. Here is what `-v3` says -- you can see it is a result of other errors triggered by missing input file:

```
[GW] sos run test.sos -v3
DEBUG: Workflow default created with 1 sections: default_1
DEBUG: Failed to load target docker_build: The 'docker' distribution was not found and is required by the application
DEBUG: Input of step default_1 is set to Undertermined: name 'files' is not defined
DEBUG: Args [x.replace('txt', 'out') for x in files], group_by = 1
 cannot be determined: name 'files' is not defined
DEBUG: Input of step default_None is set to Undertermined: name 'files' is not defined
DEBUG: Args [x.replace('txt', 'out') for x in files], group_by = 1
 cannot be determined: name 'files' is not defined
DEBUG: Master execute d61bc6959452b95fd708b3772caec07c from DAG
DEBUG: Worker SoS_Worker-1 receives request ('step', <sos.sos_script.SoS_Step object at 0x7f436b0124e0>, {'__completed__': [], '__environ_vars__': {'files', 'x', 'sos_handle_parameter_', 'globals', 'group_by'}, '__changed_vars__': set(), '__step_output__': [], '__signature_vars__': {'_output', '_input'}, '__workflow_sig__': '/home/gaow/tmp/.sos/5746c6767a76e01f.sig'}, {}, [], 'run', 'default', 3)
DEBUG: Worker SoS_Worker-1 working on a step with args []
INFO: Executing default_1: 
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.8.8-py3.5.egg/sos/sos_step.py", line 1240, in run
    res = Base_Step_Executor.run(self)
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.8.8-py3.5.egg/sos/sos_step.py", line 1240, in run
    res = Base_Step_Executor.run(self)
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.8.8-py3.5.egg/sos/sos_step.py", line 896, in run
    input_files = self.expand_input_files(stmt, *args)
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.8.8-py3.5.egg/sos/sos_step.py", line 246, in expand_input_files
    return _expand_file_list(False, *args)
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.8.8-py3.5.egg/sos/sos_step.py", line 1197, in _expand_file_list
    raise UnknownTarget(ifile)
sos.target.UnknownTarget: Target unavailable: 1.txt
DEBUG: Worker SoS_Worker-1 completes request ('step', <sos.sos_script.SoS_Step object at 0x7f436b0124e0>, {'__completed__': [], '__environ_vars__': {'files', 'x', 'sos_handle_parameter_', 'globals', 'group_by'}, '__changed_vars__': set(), '__step_output__': [], '__signature_vars__': {'_output', '_input'}, '__workflow_sig__': '/home/gaow/tmp/.sos/5746c6767a76e01f.sig'}, {}, [], 'run', 'default', 3)
DEBUG: Master receive a result
INFO: Resolving 1 objects from 1 nodes
DEBUG: default: 
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.8.8-py3.5.egg/sos/__main__.py", line 350, in cmd_run
    executor.run(args.__targets__, mode='dryrun' if args.dryrun else 'run')
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.8.8-py3.5.egg/sos/sos_executor.py", line 808, in run
    if self.resolve_dangling_targets(dag, [target]) == 0:
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.8.8-py3.5.egg/sos/sos_executor.py", line 437, in resolve_dangling_targets
    raise RuntimeError('No step to generate target {}{}'.format(target, dag.steps_depending_on(target, self.workflow)))
RuntimeError: No step to generate target 1.txt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.8.8-py3.5.egg/sos/sos_executor.py", line 1037, in run
    for p, _, _ in procs + pool:
TypeError: 'NoneType' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.8.8-py3.5.egg/sos/__main__.py", line 350, in cmd_run
    executor.run(args.__targets__, mode='dryrun' if args.dryrun else 'run')
  File "/opt/miniconda3/lib/python3.5/site-packages/sos-0.9.8.8-py3.5.egg/sos/sos_executor.py", line 1042, in run
    for _, p, _ in procs + pool:
TypeError: 'NoneType' object is not iterable
ERROR: 'NoneType' object is not iterable
```

I have removed both `.sos` and `~/.sos` but did not help. This is on a machine I infrequently use. Its conda dates back to 8 months ago as far as I can recall.

**Comment by BoPeng** [comment]
Interesting, I get this after I `pull`, I am checking.

**Comment by gaow** [comment]
Again I cannot provide a MWE to reproduce it, but I do run into a similar issue again:

```
  File "/home/gaow/Public/miniconda3/lib/python3.6/site-packages/sos-0.9.8.9-py3.6.egg/sos/sos_executor.py", line 871, in run
    if proc[2]._status == 'workflow_pending' and proc[2]._pending_workflow == res['__workflow_id__']:
TypeError: 'NoneType' object is not subscriptable
ERROR: 'NoneType' object is not subscriptable
```

Maybe you could figure out without an example what's going on here :) ?

**Comment by BoPeng** [comment]
Try again?

**Comment by gaow** [comment]
Seems fixed! :)

**Comment by gaow** [comment]
Sorry while we are in the mood for it, here is another instance that only shows up when trying to handle an exception:

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gaow/Public/miniconda3/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/gaow/Public/miniconda3/lib/python3.6/site-packages/sos-0.9.8.9-py3.6.egg/sos/sos_executor.py", line 154, in run
    self.run_workflow(*work[1:])
  File "/home/gaow/Public/miniconda3/lib/python3.6/site-packages/sos-0.9.8.9-py3.6.egg/sos/sos_executor.py", line 174, in run_workflow
    executer.run(targets=targets, parent_pipe=self.pipe, my_workflow_id=workflow_id)
  File "/home/gaow/Public/miniconda3/lib/python3.6/site-packages/sos-0.9.8.9-py3.6.egg/sos/sos_executor.py", line 1041, in run
    p.terminate()
AttributeError: 'NoneType' object has no attribute 'terminate'
```
