### ISSUE TITLE
Support for typescript.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SOS#729]
We might be able to make [`itypescript`](https://www.npmjs.com/package/itypescript) work trivially and add [TypeScript](https://www.typescriptlang.org/) as the 9th supported language.

Steps:
1. add `TypeScript` as supported language in `sos.JavaScript.kernel:sos_JavaScript`.
2. Install typescript and itypescript
3. Test if typescript works
4. if works, copy `test/JavaScript` to `test/TypeScript` and test for `typescript`. Add installation code to `.travis.yml`.

**Comment by BoPeng** [comment]
Does not work because itypescript requires `node-gyp`, which does not support Python3, and sos is based on Python3. [The ticket](https://github.com/nodejs/node-gyp/issues/193) on this issue says is an upstream issue.

```
Succesfully build libzmq on Fri Aug 04 2017 11:34:09 GMT-0500 (CDT)
gyp ERR! configure error
gyp ERR! stack Error: Python executable "/Users/bpeng1/anaconda/bin/python" is v3.5.2, which is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & < 3.0.0.
gyp ERR! stack     at failPythonVersion (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:406:14)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:395:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:204:7)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:319:11)
gyp ERR! stack     at emitOne (events.js:90:13)
gyp ERR! stack     at Socket.emit (events.js:182:7)
gyp ERR! stack     at Pipe._onclose (net.js:471:12)
gyp ERR! System Darwin 15.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/itypescript/node_modules/zeromq
gyp ERR! node -v v5.6.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
/usr/local/lib
└── (empty)
```
