### ISSUE TITLE
`docker_image` issue

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#762]
I run into the following with `docker_image`:

![2017-08-11-19-04-50_scrot](https://user-images.githubusercontent.com/917985/29235844-998e89d2-7ec8-11e7-875a-4020b45e60dd.png)

**Comment by BoPeng** [comment]
```
$ sos run test
INFO: Executing default_0:
INFO: input:    []
INFO: docker pull inutano/sra-toolkit
Using default tag: latest
latest: Pulling from inutano/sra-toolkit
96c6a1f3c3b0: Pull complete
ed40d4bcb313: Pull complete
b171f9dbc13b: Pull complete
ccfc4df4fbba: Pull complete
bcfbdd7ccc7e: Pull complete
57a4dc36dfca: Pull complete
585061109b4c: Pull complete
721ebae51fc9: Pull complete
Digest: sha256:74a7f92d88f06375e9b262486946072b0a2f5ef7b6f65450b52cd5e87c2a07f7
Status: Downloaded newer image for inutano/sra-toolkit:latest
INFO: docker run --rm   -v /Users:/Users -v /tmp:/tmp -v /Users/bpeng1/sos/tmp_425je49/docker_run_51280.sh:/var/lib/sos/docker_run_51280.sh    -t -P -w=/Users/bpeng1/sos     inutano/sra-toolkit /bin/bash /var/lib/sos/docker_run_51280.sh

Usage:
  fastq-dump [options] <path> [<path>...]
  fastq-dump [options] <accession>

INPUT
  -A|--accession <accession>       Replaces accession derived from <path> in
                                   filename(s) and deflines (only for single
                                   table dump)
  --table <table-name>             Table name within cSRA object, default is
                                   "SEQUENCE"
```

OS? Docker version?

**Comment by BoPeng** [comment]
Oh, not `docker-py`, just `docker`. Remove`docker-py` first.

**Comment by gaow** [comment]
Hmm it does not work either way. Im on the latest `master`. My OS is Debian 9. Docker version:

```
Docker version 17.06.0-ce, build 02c1d87
```
which I downloaded today via `apt-get` after adding docker repo HTTP to my `source.list`. I removed Py_Module():

```
[1]
run: docker_image = 'inutano/sra-toolkit'
    fastq-dump -h
```

I get:

```
INFO: Executing default_1: 
INFO: input:    []
DEBUG: _input: []
DEBUG: Trying paths: <filter object at 0x2aac2ca1bdd8>
DEBUG: No config file found
DEBUG: %s://%s:%s "%s %s %s" %s %s
  File "/home/gaow/Public/miniconda3/lib/python3.6/site-packages/sos-0.9.8.10-py3.6.egg/sos/sos_step.py", line 1320, in run
    res = Base_Step_Executor.run(self)
Traceback (most recent call last):
  File "/home/gaow/Public/miniconda3/lib/python3.6/site-packages/sos-0.9.8.10-py3.6.egg/sos/sos_step.py", line 828, in execute
    self.last_res = SoS_exec(stmt, self.step.sigil)
  File "/home/gaow/Public/miniconda3/lib/python3.6/site-packages/sos-0.9.8.10-py3.6.egg/sos/sos_eval.py", line 493, in SoS_exec
    res = eval(stmts, _dict)
  File "<string>", line 2, in <module>
  File "/home/gaow/Public/miniconda3/lib/python3.6/site-packages/sos-0.9.8.10-py3.6.egg/sos/actions.py", line 89, in action_wrapper
    docker.pull(kwargs['docker_image'])
  File "/home/gaow/Public/miniconda3/lib/python3.6/site-packages/sos-0.9.8.10-py3.6.egg/sos/docker/client.py", line 130, in pull
    if not self._is_image_avail(image):
AttributeError: 'function' object has no attribute 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gaow/Public/miniconda3/lib/python3.6/site-packages/sos-0.9.8.10-py3.6.egg/sos/sos_step.py", line 1320, in run
    res = Base_Step_Executor.run(self)
  File "/home/gaow/Public/miniconda3/lib/python3.6/site-packages/sos-0.9.8.10-py3.6.egg/sos/sos_step.py", line 1108, in run
    self.execute(statement[1], signatures[idx])
  File "/home/gaow/Public/miniconda3/lib/python3.6/site-packages/sos-0.9.8.10-py3.6.egg/sos/sos_step.py", line 832, in execute
    raise RuntimeError('Failed to process statement {} ({}): {}'.format(short_repr(stmt), e.__class__.__name__, e))
RuntimeError: Failed to process statement run(r"""fastq-dump -h\n""", doc...toolkit')\n (AttributeError): 'function' object has no attribute 'list'
DEBUG: Step default_1 sends exception Failed to process statement run(r"""fastq-dump -h\n""", doc...toolkit')\n (AttributeError): 'function' object has no attribute 'list'
DEBUG: Worker SoS_Worker-1 completes request ('step', <sos.sos_script.SoS_Step object at 0x2aac26fd3c50>, {'__signature_vars__': {'docker_image'}, '__environ_vars__': set(), '__changed_vars__': set(), '__step_output__': [], '__completed__': [], '__workflow_sig__': '/bioinformagics/GIT/github/sos-campaign/sos-paper/.sos/2c25ce4d97a93d7c.sig'}, {}, [], 'run', 'default', 4)
DEBUG: Master receive a result Failed to process statement run(r"""fastq-dump -h\n""", doc...toolkit')\n (AttributeError): 'function' object has no attribute 'list'
DEBUG: Master received an exception
  File "/home/gaow/Public/miniconda3/lib/python3.6/site-packages/sos-0.9.8.10-py3.6.egg/sos/__main__.py", line 350, in cmd_run
    executor.run(args.__targets__, mode='dryrun' if args.dryrun else 'run')
Traceback (most recent call last):
  File "/home/gaow/Public/miniconda3/lib/python3.6/site-packages/sos-0.9.8.10-py3.6.egg/sos/__main__.py", line 350, in cmd_run
    executor.run(args.__targets__, mode='dryrun' if args.dryrun else 'run')
  File "/home/gaow/Public/miniconda3/lib/python3.6/site-packages/sos-0.9.8.10-py3.6.egg/sos/sos_executor.py", line 1084, in run
    raise exec_error
sos.sos_executor.ExecuteError: [default_1]: Failed to process statement run(r"""fastq-dump -h\n""", doc...toolkit')\n (AttributeError): 'function' object has no attribute 'list'
ERROR: [default_1]: Failed to process statement run(r"""fastq-dump -h\n""", doc...toolkit')\n (AttributeError): 'function' object has no attribute 'list'

```

**Comment by BoPeng** [comment]
I meant the python module `docker`, not `docker-py`.

**Comment by gaow** [comment]
Ahh I see what you mean! Yes after removing `docker-py` and installing `docker` I was able to make it work. 

I will open a separate ticket to discuss a related comment.

**Comment by BoPeng** [comment]
If this is indeed the case, could you add before [this line](https://github.com/vatlab/SoS/blob/master/src/sos/docker/client.py#L85) something like

```
try:
    ...
except:
    raise RuntimeError("Incompatible docker module. Please use docker (version ...) instead of docker-py.
```
