### ISSUE TITLE
sos executor bug

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#765]
This bug below can be reproduced by the [`jnbinder` example](https://github.com/stephenslab/ipynb-website) -- to reproduce, clone the repo and run `./release.sos`:

```
Process SoS_Worker-2:
Traceback (most recent call last):
  File "/home/gaow/Public/miniconda3/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/gaow/Public/miniconda3/lib/python3.6/site-packages/sos-0.9.8.10-py3.6.egg/sos/sos_executor.py", line 153, in run
    self.run_workflow(*work[1:])
  File "/home/gaow/Public/miniconda3/lib/python3.6/site-packages/sos-0.9.8.10-py3.6.egg/sos/sos_executor.py", line 173, in run_workflow
    executer.run(targets=targets, parent_pipe=self.pipe, my_workflow_id=workflow_id)
  File "/home/gaow/Public/miniconda3/lib/python3.6/site-packages/sos-0.9.8.10-py3.6.egg/sos/sos_executor.py", line 1055, in run
    raise e
  File "/home/gaow/Public/miniconda3/lib/python3.6/site-packages/sos-0.9.8.10-py3.6.egg/sos/sos_executor.py", line 810, in run
    runnable._depends_targets.append(target)
AttributeError: 'Undetermined' object has no attribute 'append'
```

**Comment by BoPeng** [comment]
This is caused by some recent change on how `depends` are handled. The patch is easy but we might be bitten by this in some other places...

**Comment by gaow** [comment]
[`jnbinder` example](https://github.com/stephenslab/ipynb-website) still not working:

```
AttributeError: 'SoS_Node' object has no attribute '_depends'
```

**Comment by gaow** [comment]
Still not working -- the jnbinder example ends up in an infinite loop.

**Comment by BoPeng** [comment]
An obvious bug, we should really add more unit tests.
