### ISSUE TITLE
Remote job broken

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#798]
This is what I get running remote job.

```
DEBUG: Master receives task request tasks midway2 2a016bcec560ce2d49e8502ca2820b1a b0afded81f11c72624a67f4d45acfcbc f0190e387c35b914327a350d5865b1f6 fc84f836cd4c7bd84c10cf73265850f6 4cc73e41f0785a19edd5e44e40108f7d 00b671fcb24dc370289c6ce2d10624ab 02f9fb611ba9b619ae6f72e175de20f2 5f4bdd0d4112b9d65657f2ec4a55db43 fc898f50fb3a545b9db2196ab28a6c05 90003f7a50e12491aef83776d7f083d3 9f33a37f50bd39e65a6fa1895043ba21 165347e70df2dfad15333a8f47e4b67a a1dbaa479723ff2c0d2c467ac1cc399d 2280b287361feb8d20dbbf3b5408435e 81df3f354fd6b1dde288a81b260a958c ef319d9fe7589e5c6d5b8eb5b80635b8 508c0b24553ac41effc377195bc0bcbe 3570e1e7a2e7532dc80c556e116950af 337a5aed49a05ef46a20be861abf6b19 726586b3c1505b2fb38c7a0710200c24 bbedbb31e2ca2a0f2cdd9308a543ac8e fdd2e35cd7ad4e2d1c3641eb98d834ee d209ecb748d9b9acbe055120e334b15a ed64a7b5b1d698b3c2c739a269481414 b66bbd629acc852dfb782489323be792 19a74c0f4dba542d1a88a243d640d70d c2db27d21e605495c86dee64f0cf6b32 1b7fb2a583ffaec77124510ec4d872cb 97d55e88062166852c863098666a1951 c5691a695a251b2712f4d51af2568e64 a41f043a992a218a107a82cb19739593 41b338c4845b0bcf267adce79531c2b8 27b8b1f91d875c2662b68b0e552fe0ed 7e3bcdd00cb70599a8665851455f1395 ee8dcea6dfd1f30a3a3a9ef9dbc4df68 87337074b7443f05a0866231801aacff d418b160207c40aabe19582f404a8b51 c32e6c8082d86497c1646048ad04bfd1
DEBUG: Executing command ssh -q gaow@midway.rcc.uchicago.edu -p 22 "bash --login -c '[ -d /home/gaow/GIT/github/admix-phase ] || mkdir -p /home/gaow/GIT/github/admix-phase; cd /home/gaow/GIT/github/admix-phase && sos status  -v 2  --start-time '" 
TRACE: Step becomes task_pending
TRACE: Start submitting 2a016bcec560ce2d49e8502ca2820b1a (status: pending)
TRACE: Start submitting b0afded81f11c72624a67f4d45acfcbc (status: pending)
TRACE: Start submitting f0190e387c35b914327a350d5865b1f6 (status: pending)
TRACE: Start submitting fc84f836cd4c7bd84c10cf73265850f6 (status: pending)
TRACE: Start submitting 4cc73e41f0785a19edd5e44e40108f7d (status: pending)
ERROR: '<' not supported between instances of 'int' and 'str'
TRACE: Start submitting 00b671fcb24dc370289c6ce2d10624ab (status: pending)
TRACE: Start submitting 02f9fb611ba9b619ae6f72e175de20f2 (status: pending)
TRACE: Start submitting 5f4bdd0d4112b9d65657f2ec4a55db43 (status: pending)
TRACE: Start submitting fc898f50fb3a545b9db2196ab28a6c05 (status: pending)
TRACE: Start submitting 90003f7a50e12491aef83776d7f083d3 (status: pending)
ERROR: '<' not supported between instances of 'int' and 'str'
TRACE: Start submitting 9f33a37f50bd39e65a6fa1895043ba21 (status: pending)
TRACE: Start submitting 165347e70df2dfad15333a8f47e4b67a (status: pending)
TRACE: Start submitting a1dbaa479723ff2c0d2c467ac1cc399d (status: pending)
ERROR: '<' not supported between instances of 'int' and 'str'
TRACE: Start submitting 2280b287361feb8d20dbbf3b5408435e (status: pending)
TRACE: Start submitting 81df3f354fd6b1dde288a81b260a958c (status: pending)
ERROR: '<' not supported between instances of 'int' and 'str'
TRACE: Start submitting ef319d9fe7589e5c6d5b8eb5b80635b8 (status: pending)
TRACE: Start submitting 508c0b24553ac41effc377195bc0bcbe (status: pending)
TRACE: Start submitting 3570e1e7a2e7532dc80c556e116950af (status: pending)
TRACE: Start submitting 337a5aed49a05ef46a20be861abf6b19 (status: pending)
TRACE: Start submitting 726586b3c1505b2fb38c7a0710200c24 (status: pending)
ERROR: '<' not supported between instances of 'int' and 'str'
TRACE: Start submitting bbedbb31e2ca2a0f2cdd9308a543ac8e (status: pending)
TRACE: Start submitting fdd2e35cd7ad4e2d1c3641eb98d834ee (status: pending)
ERROR: '<' not supported between instances of 'int' and 'str'
TRACE: Start submitting d209ecb748d9b9acbe055120e334b15a (status: pending)
TRACE: Start submitting ed64a7b5b1d698b3c2c739a269481414 (status: pending)
TRACE: Start submitting b66bbd629acc852dfb782489323be792 (status: pending)
TRACE: Start submitting 19a74c0f4dba542d1a88a243d640d70d (status: pending)
ERROR: '<' not supported between instances of 'int' and 'str'
TRACE: Start submitting c2db27d21e605495c86dee64f0cf6b32 (status: pending)
TRACE: Start submitting 1b7fb2a583ffaec77124510ec4d872cb (status: pending)
TRACE: Start submitting 97d55e88062166852c863098666a1951 (status: pending)
ERROR: '<' not supported between instances of 'int' and 'str'
TRACE: Start submitting c5691a695a251b2712f4d51af2568e64 (status: pending)
TRACE: Start submitting a41f043a992a218a107a82cb19739593 (status: pending)
TRACE: Start submitting 41b338c4845b0bcf267adce79531c2b8 (status: pending)
ERROR: '<' not supported between instances of 'int' and 'str'
TRACE: Start submitting 27b8b1f91d875c2662b68b0e552fe0ed (status: pending)
TRACE: Start submitting 7e3bcdd00cb70599a8665851455f1395 (status: pending)
TRACE: Start submitting ee8dcea6dfd1f30a3a3a9ef9dbc4df68 (status: pending)
ERROR: '<' not supported between instances of 'int' and 'str'
TRACE: Start submitting 87337074b7443f05a0866231801aacff (status: pending)
TRACE: Start submitting d418b160207c40aabe19582f404a8b51 (status: pending)
TRACE: Start submitting c32e6c8082d86497c1646048ad04bfd1 (status: pending)
ERROR: '<' not supported between instances of 'int' and 'str'
ERROR: '<' not supported between instances of 'int' and 'str'
ERROR: '<' not supported between instances of 'int' and 'str'
ERROR: '<' not supported between instances of 'int' and 'str'
ERROR: '<' not supported between instances of 'int' and 'str'
ERROR: '<' not supported between instances of 'int' and 'str'
ERROR: '<' not supported between instances of 'int' and 'str'
ERROR: '<' not supported between instances of 'int' and 'str'
ERROR: '<' not supported between instances of 'int' and 'str'
ERROR: '<' not supported between instances of 'int' and 'str'
ERROR: '<' not supported between instances of 'int' and 'str'
ERROR: '<' not supported between instances of 'int' and 'str'
ERROR: '<' not supported between instances of 'int' and 'str'
ERROR: '<' not supported between instances of 'int' and 'str'
ERROR: '<' not supported between instances of 'int' and 'str'
ERROR: '<' not supported between instances of 'int' and 'str'
ERROR: '<' not supported between instances of 'int' and 'str'
ERROR: '<' not supported between instances of 'int' and 'str'
ERROR: '<' not supported between instances of 'int' and 'str'
ERROR: '<' not supported between instances of 'int' and 'str'
ERROR: '<' not supported between instances of 'int' and 'str'
ERROR: '<' not supported between instances of 'int' and 'str'
ERROR: '<' not supported between instances of 'int' and 'str'
ERROR: '<' not supported between instances of 'int' and 'str'
ERROR: '<' not supported between instances of 'int' and 'str'
ERROR: '<' not supported between instances of 'int' and 'str'
ERROR: '<' not supported between instances of 'int' and 'str'
ERROR: '<' not supported between instances of 'int' and 'str'
DEBUG: scp -P 22 -p -q gaow@midway.rcc.uchicago.edu:.sos/tasks/2a016bcec560ce2d49e8502ca2820b1a.* /home/gaow/.sos/tasks
scp: .sos/tasks/2a016bcec560ce2d49e8502ca2820b1a.*: No such file or directory
  File "/home/gaow/Public/miniconda3/lib/python3.6/site-packages/sos-0.9.8.10-py3.6.egg/sos/__main__.py", line 350, in cmd_run
    executor.run(args.__targets__, mode='dryrun' if args.dryrun else 'run')
Traceback (most recent call last):
  File "/home/gaow/Public/miniconda3/lib/python3.6/site-packages/sos-0.9.8.10-py3.6.egg/sos/__main__.py", line 350, in cmd_run
    executor.run(args.__targets__, mode='dryrun' if args.dryrun else 'run')
  File "/home/gaow/Public/miniconda3/lib/python3.6/site-packages/sos-0.9.8.10-py3.6.egg/sos/sos_executor.py", line 1056, in run
    raise e
  File "/home/gaow/Public/miniconda3/lib/python3.6/site-packages/sos-0.9.8.10-py3.6.egg/sos/sos_executor.py", line 900, in run
    task_status = proc[2]._host.retrieve_results(proc[2]._pending_tasks)
  File "/home/gaow/Public/miniconda3/lib/python3.6/site-packages/sos-0.9.8.10-py3.6.egg/sos/hosts.py", line 879, in retrieve_results
    return {task: self._host_agent.receive_result(task) for task in tasks}
  File "/home/gaow/Public/miniconda3/lib/python3.6/site-packages/sos-0.9.8.10-py3.6.egg/sos/hosts.py", line 879, in <dictcomp>
    return {task: self._host_agent.receive_result(task) for task in tasks}
RuntimeError: Failed to retrieve result of job 2a016bcec560ce2d49e8502ca2820b1a from midway2 with cmd
scp -P 22 -p -q gaow@midway.rcc.uchicago.edu:.sos/tasks/2a016bcec560ce2d49e8502ca2820b1a.* /home/gaow/.sos/tasks
ERROR: Failed to retrieve result of job 2a016bcec560ce2d49e8502ca2820b1a from midway2 with cmd
scp -P 22 -p -q gaow@midway.rcc.uchicago.edu:.sos/tasks/2a016bcec560ce2d49e8502ca2820b1a.* /home/gaow/.sos/tasks
```

I think the same script has always worked. Maybe something is broken lately.

**Comment by BoPeng** [comment]
Try to identify the problem. Do you see the `<` error when you execute the command with `sos execute -q`?

**Comment by gaow** [comment]
No, it seems Ok with that command.

**Comment by BoPeng** [comment]
The message is a bit strange because there is no indication of what fails... as other messages usually say `... failed: message`.

**Comment by BoPeng** [comment]
I fixed all tests in Travis CI and could not find this one, so it might be script or server configuration specific. Please send me your `script` and `hosts.yml` (via private email if you prefer) so that I can try to reproduce it.
