### ISSUE TITLE
SoS does not quit cleanly with exception from worker

### ISSUE THREAD

**Issue by BoPeng** [vatlab/SoS#838]
SoS hangs when one of the workers raises an exception.

```
$ sos run Summarize_RNASeq.ipynb --dir ~/rsrch1/RNASeqV2/IPCT/Projects/PHLT0001
INFO: Executing default_0:
INFO: input:    []
INFO: Resolving 14 objects from 1 nodes
Process SoS_Worker-2:
Traceback (most recent call last):
  File "/Users/bpeng1/anaconda/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/Users/bpeng1/anaconda/lib/python3.6/site-packages/sos-0.9.9.9-py3.6.egg/sos/sos_executor.py", line 153, in run
    self.run_workflow(*work[1:])
  File "/Users/bpeng1/anaconda/lib/python3.6/site-packages/sos-0.9.9.9-py3.6.egg/sos/sos_executor.py", line 173, in run_workflow
    executer.run(targets=targets, parent_pipe=self.pipe, my_workflow_id=workflow_id)
  File "/Users/bpeng1/anaconda/lib/python3.6/site-packages/sos-0.9.9.9-py3.6.egg/sos/sos_executor.py", line 687, in run
    dag = self.initialize_dag(targets=targets)
  File "/Users/bpeng1/anaconda/lib/python3.6/site-packages/sos-0.9.9.9-py3.6.egg/sos/sos_executor.py", line 632, in initialize_dag
    self.resolve_dangling_targets(dag, targets)
  File "/Users/bpeng1/anaconda/lib/python3.6/site-packages/sos-0.9.9.9-py3.6.egg/sos/sos_executor.py", line 442, in resolve_dangling_targets
    raise RuntimeError('No step to generate target {}{}'.format(target, dag.steps_depending_on(target, self.workflow)))
RuntimeError: No step to generate target /Users/bpeng1/rsrch1/RNASeqV2/IPCT/Projects/PHLT0001/IPCT-PHLT0001-24112-208023-B-TU-F01/IPCT-PHLT0001-24112-208023-B-TU-F01.snpEff.vcf.gz requested by merge-vcf_0
```

Assuming this can happen with other programs, `interrupt` from sos notebook should kill the subprocess, not the kernel. The latter is the case right now.

**Comment by BoPeng** [comment]
It might also be the case that other workers are working, so it is not entirely sure if we should change the behavior.
