### ISSUE TITLE
Docker user ID match issue

### ISSUE THREAD

**Issue by gaow** [vatlab/SoS#951]
So I've being trying to distribute dockerized SoS applications. It is a lot more difficult to get things work compared to other typical docker apps, mostly because SoS creates 1) `$HOME/.sos` and 2) `$PWD/.sos`. It takes numerous trial and errors to get it almost working on a couple of Linux and Mac machines. Because there are just permission issues with either 1) or 2). 

So far, this is what I think is closest to run dockerized SoS:

```
 docker run --security-opt label:disable -t -P \
    -w $PWD -v $HOME:$HOME -v /tmp:/tmp -v $PWD:$PWD -u $UID 
    -e HOME=$HOME
```

the only line I have to add in addition to SoS `docker_image` default is the last line `-e HOME=$HOME`. Otherwise it will attempt to create `/.sos`. 

Now I'm still having an error:

```
DEBUG: Workflow default created with 1 sections: default_0
  File "/opt/miniconda3/lib/python3.6/site-packages/sos/__main__.py", line 383, in cmd_run
    executor.run(args.__targets__, mode='dryrun' if args.dryrun else 'run')
Traceback (most recent call last):
  File "/opt/miniconda3/lib/python3.6/site-packages/sos/__main__.py", line 383, in cmd_run
    executor.run(args.__targets__, mode='dryrun' if args.dryrun else 'run')
  File "/opt/miniconda3/lib/python3.6/site-packages/sos/workflow_executor.py", line 792, in run
    self.reset_dict()
  File "/opt/miniconda3/lib/python3.6/site-packages/sos/workflow_executor.py", line 428, in reset_dict
    load_config_files(self.config['config_file'])
  File "/opt/miniconda3/lib/python3.6/site-packages/sos/utils.py", line 1057, in load_config_files
    cfg['user_name'] = getpass.getuser().lower()
  File "/opt/miniconda3/lib/python3.6/getpass.py", line 169, in getuser
    return pwd.getpwuid(os.getuid())[0]
KeyError: 'getpwuid(): uid not found: 1002'
ERROR: 'getpwuid(): uid not found: 1002'
```

I'm sure it is not readily reproducible, because it involves running under and account whose UID is not in the docker container. But if there is such a machine, then to reproduce:

```bash
docker run --security-opt label:disable -t -P -w $PWD -v $HOME:$HOME \
    -v /tmp:/tmp -v $PWD:$PWD -u $UID \
    -e HOME=$HOME python:3.6.5-alpine sh -c \
    'python -c "import getpass; getpass.getuser()"'
```

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/getpass.py", line 169, in getuser
    return pwd.getpwuid(os.getuid())[0]
KeyError: 'getpwuid(): uid not found: 1002'
```

I'm still fiddling, but would be great if there are comments to drop. And when it eventually works for me we should keep the solution for future reference or even put into our documentation.

**Comment by gaow** [comment]
To show how SoS fail without setting `-e HOME=$HOME`, 

```
docker run --security-opt label:disable -t -P -w $PWD -v $HOME:$HOME    \
         -v /tmp:/tmp -v $PWD:$PWD -u $UID   \
         python:3.6.5-alpine sh -c  'mkdir -p $HOME/.sos; mkdir -p $PWD/.sos'
```
```
mkdir: can't create directory '//.sos': Permission denied
```

**Comment by BoPeng** [comment]
Sorry that you had to fight these alone because I do not have a linux environment to work with. Let me see if I can find one.

**Comment by gaow** [comment]
@BoPeng Oh thanks a lot! actually you can log in to the SoS server and test out those command I have above. Let me make sure it also fails there.

**Comment by gaow** [comment]
Indeed it can be reproduced on the SoS server:

```
sos@shiny:~$ docker run --security-opt label:disable -t -P -w $PWD -v $HOME:$HOME    \
>          -v /tmp:/tmp -v $PWD:$PWD -u $UID   \
>          python:3.6.5-alpine sh -c \
>          'mkdir -p $HOME/.sos; mkdir -p $PWD/.sos'
mkdir: can't create directory '//.sos': Permission denied
sos@shiny:~$ 
sos@shiny:~$ docker run --security-opt label:disable -t -P -w $PWD -v $HOME:$HOME \
>     -v /tmp:/tmp -v $PWD:$PWD -u $UID \
>     -e HOME=$HOME python:3.6.5-alpine sh -c \
>     'python -c "import getpass; getpass.getuser()"'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/getpass.py", line 169, in getuser
    return pwd.getpwuid(os.getuid())[0]
KeyError: 'getpwuid(): uid not found: 1005'
```

**Comment by gaow** [comment]
Ahh I think I got it: `-u $UID -e HOME=$HOME -e USER=$USER` seem to work!
